<a href="https://colab.research.google.com/github/projectwint/practice_AI/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%ED%95%A8%EC%88%98%EC%99%80_%EB%AC%B8%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***array와 asarray***
출처 : https://ok-lab.tistory.com/179

구조적으로 동일 </br>
차이점 : array는 copy=True, asarray는 copy=False </br>
즉, array는 원본 변경시 복사본 변경 X, asarray는 원본 변경시 복사본 변경 O

In [ ]:
import numpy as np

a = np.ones([3, 4]) #1로 차있는 3, 4 형태 배열 생성

a_array = np.array(a)
a_asarray = np.asarray(a)

a[1] = 0

print(f'a_array \n {a_array} \n')
print(f'a_asarray \n {a_asarray} \n')

a_array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

a_asarray 
 [[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]] 



# ***train_test_split 모듈***
출처 : https://teddylee777.github.io/scikit-learn/train-test-split

사이킷런(scikit-learn)의 model_selection 패키지 안에 train_test_split 모듈을 활용하여 학습 데이터 셋과 테스트 셋을 분리할 수 있다.

***train(학습 셋) / test(테스트 셋) 분리 이유?***

머신러닝 모델에 train 데이터를 100% 학습시킨 후 test 데이터에 모델을 적용했을 때 성능이 생각보다 안 나오는 경우(Overfitting)가 생김.

모델이 내가 가진 학습 데이터에 너무 과적합되도록 학습하여여, 이를 조금이라도 벗어난 케이스에 대해서는 예측율이 현저히 떨어진다.

따라서 기존 train / test로 구분 되어 있었던 데이터 셋을 train에서 train / validation으로 일정 비율 쪼갠 다음에 학습 시에는 train(학습) 셋으로 학습 후 중간중간 validation(테스트) 셋으로 내가 학습한 모델 평가를 해주는 것


In [ ]:
from sklearn.datasets import load_iris # 샘플 데이터 로딩
from sklearn.model_selection import train_test_split

# load sample
dataset = load_iris()

data = dataset['data']
target = dataset['target']

# train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(data, target, test_size=0.2, shuffle=True, stratify=target, random_state=34)

***옵션 값 설명***

test_size : 테스트 셋 구성 비율. train_size의 옵션과 반대 관계. (주로 test_size를 지정) 0.2는 전체 데이터 셋의 20%를 test (validation) 셋으로 지정하겠다는 의미. **default=0.25**

shuffle: split을 해주기 이전에 섞을건지 여부. 보통은 default 값으로 놔둠. **default=True**

stratify: classification을 다룰 때 매우 중요한 옵션값. stratify 값을 target으로 지정해주면 각각의 class 비율(ratio)을 train / validation에 유지. (한 쪽에 쏠려서 분배되는 것을 방지) 만약 이 옵션을 지정해 주지 않고 classification 문제를 다룬다면, 성능의 차이가 많이 날 수 있다. **default=None**

random_state: 세트를 섞을 때 해당 int 값을 보고 섞으며, 하이퍼 파라미터를 튜닝시 이 값을 고정해두고 튜닝해야 매번 데이터셋이 변경되는 것을 방지할 수 있다.

# ***glob.glob()***
glob 모듈의 glob 함수 - 파일명을 리스트 형식으로 반환환

출처 : https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=siniphia&logNo=221397012627

dir폴더의 모든 파일 목록

dir : file1.txt, file2.txt, file101.txt, file102.txt, filea.txt, fileb.txt, file1.jpg, file2.jpg

```
import glob

# '*'는 임의 길이의 모든 문자열을 의미한다.
>>> output = glob.glob('dir/*.txt')
>>> print(output)
['dir\\file1.txt', 'dir\\file101.txt', 'dir\\file102.txt', 'dir\\file2.txt', 'dir\\filea.txt', 'dir\\fileb.txt']

# '?'는 한자리의 문자를 의미한다.
>>> output = glob.glob('dir/file?.*')
>>> print(output)
['dir\\file1.bmp', 'dir\\file1.txt', 'dir\\file2.bmp', 'dir\\file2.txt', 'dir\\filea.txt', 'dir\\fileb.txt']

# recursive=True로 설정하고 '**'를 사용하면 모든 하위 디렉토리까지 탐색한다.
# 기본값은 False이며, 파일이 너무 많을 경우에 사용하면 과도한 cost가 소모된다고 한다.

```

# ***예외처리***
파이썬에서 오류를 처리하는 방법

출처 : https://wikidocs.net/30

***try, except문***

try 블록 수행 중 오류가 발생하면 except 블록이 수행된다. 하지만 try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.


```
try:
    ...
except [발생오류 [as 오류변수]]:
    ...
```



In [ ]:
#오류 종류에 상관없이
try:
    ...
except:
    ...

#특정 오류에만
try:
    ...
except 발생오류:
    ...

#오류의 내용까지 알고 싶을 때
try:
    4 / 0
except ZeroDivisionError as e:
    print(e)

division by zero


여러개 오류 처리




In [ ]:
try:
    a = [1,2]
    print(a[3])
    4/0 #여기에 오기 전에 인덱싱 오류가 이미 발생
except ZeroDivisionError: #실행 X
    print("0으로 나눌 수 없습니다.")
except IndexError:
    print("인덱싱 할 수 없습니다.")

#한꺼번에
try:
    a = [1,2]
    print(a[3])
    4/0
except (ZeroDivisionError, IndexError) as e: #먼저 발생한 오류 하나 출력
    print(e)

인덱싱 할 수 없습니다.
list index out of range


**try .. finally**

try문에는 finally절을 사용할 수 있다. finally절은 try문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다. 보통 finally절은 사용한 리소스를 close해야 할 때에 많이 사용한다.


```
try:
    f = open('foo.txt', 'w')
    # 무언가를 수행한다.

    (... 생략 ...)

finally:
    f.close()  # 중간에 오류가 발생하더라도 무조건 실행된다.
```



***try .. else***

try문에는 else절도 사용 가능하다.



```
try:
    ...
except [발생오류 [as 오류변수]]:
    ...
else:  # 오류가 없을 경우에만 수행된다.
    ...
```



In [ ]:
try:
    age=int(input('나이를 입력하세요: '))
except: #입력이 숫자가 아니어서 오류 발생할 경우
    print('입력이 정확하지 않습니다.')
else:
    if age <= 18:
        print('미성년자는 출입금지입니다.')
    else:
        print('환영합니다.')

나이를 입력하세요: 16
미성년자는 출입금지입니다.


# ***enumerate()***

출처 : https://www.daleseo.com/python-enumerate/

기본적으로 인덱스와 원소로 이루어진 튜플을 만들어줌.


In [ ]:
for entry in enumerate(['A', 'B', 'C']):
    print(entry)

(0, 'A')
(1, 'B')
(2, 'C')


인덱스와 원소를 각각 다른 변수에 할당하고 싶다면 인자 풀기(unpacking)을 해줘야 함.


```
#참고로 각 변수에 인자풀기(unpacking)로 나눠서 할당 가능
for i, j, k in [['a', 'b', 'c'], ['d', 'e', 'f']]:
    print(i, j, k)
#결과
#a b c
#d e f
```







In [ ]:
for i, letter in enumerate(['A', 'B', 'C']):
     print(i, letter)

0 A
1 B
2 C


시작 인덱스 변경

In [ ]:
#enumerate() 함수를 호출할 때 start 인자에 시작하고 싶은 숫자를 넘기기기
for i, letter in enumerate(['A', 'B', 'C'], start=1):
     print(i, letter)

1 A
2 B
3 C


***enumerate() 자체는?***



파이썬에서 for 문은 내부적으로 in 뒤에 오는 목록을 대상으로 계속해서 next() 함수를 호출하고 있다고 생각할 수 있다.

일반 리스트를 iter() 함수에 넘겨 반복자(iterator)로 만든 후 next() 함수를 호출해보면 원소들이 차례로 얻어진다.

In [ ]:
iter_letters = iter(['A', 'B', 'C'])
print(next(iter_letters))
print(next(iter_letters))
next(iter_letters)

A
B


'C'

enumerate() 함수를 호출한 결과를 대상으로 next() 함수를 계속해서 호출해보면, 인덱스와 원소의 쌍이 튜플(tuple)의 형태로 차례로 얻어진다.

In [ ]:
enumerate_letters = enumerate(['A', 'B', 'C'])
next(enumerate_letters)

(0, 'A')

결론 : enumerate() 함수는 인자로 넘어온 목록을 기준으로 인덱스와 원소를 차례대로 접근하게 해주는 반복자(iterator) 객체를 반환해주는 함수이다.

In [ ]:
list(enumerate(['A', 'B', 'C']))

[(0, 'A'), (1, 'B'), (2, 'C')]

# ***numpy로 배열 기능 사용하기***

출처: https://datascienceschool.net/01%20python/03.01%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4.html

기본적으로 파이썬은 리스트를 제공한다. <br>
리스트는 데이터 자료형이 달라도 쓸 수 있고, 원소의 개수를 유동적으로 사용할 수 있다. 하지만 리스트의 단점은 속도가 느리고 메모리를 많아 차지한다. <br>
numpy를 사용하면 배열(array)를 사용할 수 있는데, C 언어로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르다. <br>
numpy의 **array**함수를 사용하면 **ndarray** 클래스 객체(=배열)로 변환해준다. 

In [ ]:
import numpy as np

arr = np.array([0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2])

print("배열 요소 중 0의 개수는 :", len(arr[arr == 0]))
print("배열 요소 중 1의 개수는 :", len(arr[arr == 1]))
print("배열 요소 중 2의 개수는 :", len(arr[arr == 2]))

배열 요소 중 0의 개수는 : 10
배열 요소 중 1의 개수는 : 13
배열 요소 중 2의 개수는 : 4


일반적인 파이썬의 리스트에서 요소의 개수를 셀 때는 list.count(값) 방법으로 셀 수 있다. <br>
하지만 np.array로 배열을 만들어주게 되면, 배열에는 count 기능이 없어서 할 수 없다고 오류가 뜨는데 이 때는 len(array[array == 값])의 방법으로 셀 수 있다. 

# ***pickle이란?***
출처 : https://korbillgates.tistory.com/173



텍스트 상태의 데이터가 아닌 파이썬 객체 자체를 파일로 저장하는 것이다. 미리 필요한 부분을 딕셔너리 던, 리스트 던, 튜플 등으로 저장을 해놓고(이러한 형태는 파일로 바로 저장할 수 없으니), pickle 모듈을 사용해 그 객체 자체를 바이너리로 저장하는 것이다. 불러올 때도 그 자체로 불러오므로 속도가 빨라진다.

np.load() 옵션 중 allow_pickle가 디폴트가 False이므로 이를 True로 설정해주어야 한다.  https://numpy.org/devdocs/reference/generated/numpy.load.html </br>
그러지 않으면 ValueError: Object arrays cannot be loaded when allow_pickle=False 에러가 발생할 수 있다. https://kosb.tistory.com/77 

# ***bincount()***
출처 : https://nurilee.com/2020/05/10/bincount-%EB%9E%80/


0부터 가장 큰 값까지 각각의 발생 빈도수를 리스트로 반환한다. 0의 빈도는 인덱스 0에, 1의 빈도는 인덱스 1에 저장되는 형식.

In [ ]:
import numpy as np
l = [3, 4, 1, 1, 2, 2, 2, 3, 3, 5]
print(np.bincount(l))

[0 2 3 3 1 1]


# ***파이썬 버전 확인***
출처 : https://bskyvision.com/entry/python-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%B2%84%EC%A0%84-%ED%99%95%EC%9D%B8%ED%95%98%EB%8A%94-%EC%BD%94%EB%93%9C

In [ ]:
import sys
print(sys.version)

3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]


# ***가중치 (model.fit() 함수의 class_weight 옵션)***
참고 문헌 : 텐서플로2로 배우는 금융 머신러닝, 이사야 헐, 에이콘출판

이미지 분류에서 두 데이터 양 사이의 차이가 클 경우 학습이 제대로 이루어지지 않을 수 있다. 따라서 이를 방지하기 위해 가중치를 부여하여 두 데이터 간의 비율을 맞춰주는 역할을 한다고 할 수 있다.

가중치를 계산하는 법은 간단하다. y_train은 0과 1로 이루어진 인덱스를 저장한 리스트이므로 numpy 모듈을 사용해 평균을 구해주면 인덱스 1인 데이터의 비율을 구할 수 있게 된다. 이를 인덱스 0의 가중치로 부여하는 것이다. 반대로 인덱스 0인 데이터의 비율은 1에서 앞서 구한 인덱스 1인 데이터의 비율을 빼면 된다. 이를 인덱스 1의 가중치로 부여하는 것이다. 이 내용을 코드로 나타내면 다음과 같다.

In [ ]:
w0 = np.mean(y_train)
w1 = 1 - w0
class_weights = {0: w0, 1: w1}